---
- name: Ensure we are using pacman
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use pacman as a package manager."
  when: ansible_pkg_mgr != "pacman"

- name: Install Python tool dependencies via pacman
  when: python_tool_dep_pkgs is defined and python_tool_dep_pkgs | length > 0
  block:
    - name: Ensure Python tool dependencies are installed
      community.general.pacman:
        name: "{{ package }}"
        state: present
      loop: "{{ python_tool_dep_pkgs }}"
      loop_control:
        loop_var: package
      become: true
