---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Install Python via apk
  block:
    - name: Update apk cache
      community.general.apk:
        update_cache: true
      changed_when: false # The apk module currently does not support cache_valid_time.
      become: true

    - name: Ensure Python is installed
      community.general.apk:
        name: "{{ package }}"
        state: present
      loop: "{{ python_distro_pkgs }}"
      loop_control:
        loop_var: package
      become: true
