---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Install Python dependencies via apk
  block:
    - name: Update apk cache
      community.general.apk:
        update_cache: true
      changed_when: false # The apk module currently does not support cache_valid_time.
      become: true

    - name: Get Python version from package manager
      ansible.builtin.command:
        cmd: "apk info {{ python_distro_pkgs[0] }}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: python_pkg_mgr_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        python_pkg_mgr_version: "{{ (python_pkg_mgr_version_cmd.stdout | regex_search('-([0-9]+(?:\\.[0-9]+)*)-r[0-9]+', '\\1', multiline=True))[0] }}"

    - name: Debug Python version from package manager
      ansible.builtin.debug:
        var: python_pkg_mgr_version
